# $HOME/.config/alacritty/alacritty.toml
# by Ogglord 2024-02-26

[font]
#normal.family = "SauceCodePro Nerd Font"
#normal.family = "SauceCodePro Nerd Font"
normal.family = "MesloLGL Nerd Font"
size = 13.0

[window]
dimensions.columns = 120
dimensions.lines = 30
padding.x = 8
padding.y = 5

decorations = "Transparent"
decorations_theme_variant = "None" # "Dark"

opacity = 0.9
blur = true

option_as_alt = "OnlyLeft"

[env]
TERM = "term-256color"

[selection]
semantic_escape_chars =''
save_to_clipboard = true