# $HOME/.config/alacritty/alacritty.toml
# by Ogglord 2024-02-26

[font]
#normal.family = "SauceCodePro Nerd Font"
#normal.family = "SauceCodePro Nerd Font"
normal.family = "MesloLGL Nerd Font"
size = 14.0

[window]

padding.x = 8
padding.y = 5

decorations = "Transparent"
decorations_theme_variant = "None" # "Dark"

opacity = 0.9
blur = true

option_as_alt = "OnlyLeft"

[env]
TERM = "term-256color"