#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

OS=$(uname)
case $OS in
    Darwin)
         # darwin.conf.yaml
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "dotbot-brew" -c "${OS}${SUFFIX}" "${@}"
        ;;
    Linux)
    source /etc/os-release
    case $ID in
        arch)
            # opensuse.conf.yaml
            sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "dotbot_plugin_zypper" -c "${ID}${SUFFIX}" "${@}"
            ;;
        debian)
            # debian.conf.yaml
            sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "dotbot_apt" -c "${ID}${SUFFIX}" "${@}"
            ;;
        *)
            echo "unknown linux distro ID: $ID, not doing anything special"
            ;;
    esac
    ;;
    *)
        echo "Unknown OS: $OS, not doing anything special"
        ;;
esac


