#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

OS=$(uname)
case $OS in
    Darwin)
        echo "darwin" # darwin.conf.yaml
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${OS}${SUFFIX}" --plugin-dir "dotbot-brew" "${@}"
        ;;
    Linux)
    source /etc/os-release
    case $ID in
        arch)
            echo "opensuse" # opensuse.conf.yaml
            sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${ID,,}${SUFFIX}" --plugin-dir "${BASEDIR}/dotbot_plugin_zypper" "${@}"
            ;;
        debian)
            echo "debian" # debian.conf.yaml
            sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${ID,,}${SUFFIX}" --plugin-dir "${BASEDIR}/dotbot_apt" "${@}"
            ;;
        *)
            echo "unknown linux distro ID: $ID, not doing anything special"
            ;;
    esac
    ;;
    *)
        echo "Unknown OS: $OS, not doing anything special"
        ;;
esac


