## run for login shells
export EDITOR=/bin/nano
SILENT=1 _source "${ZDOTDIR}/motd.zsh"

if [[ -d /opt/homebrew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

_source "$HOME/.local/share/cargo/env"

echo "Hello, $USER. Welcome to the shell."