typeset -U path PATH
path+=~/.local/bin
path+=~/.local/share/npm/bin
path+=~/.local/share/cargo/bin
export PATH

skip_global_compinit=1

export RUSTUP_HOME="$HOME/.local/share/rustup"
export CARGO_HOME="$HOME/.local/share/cargo"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache/"

export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_FIXTERM=false
export TERM="screen-256color"

## let gnome-keyring-daemon handle unlocking of (password protected) ssh keys
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/keyring/ssh

## enable mangohud for all vulkan games
export MANGOHUD=1

function _source {
  for file in "$@"; do
    if [ -r "$file" ]; then
      source "$file"
    else
      if ! [[ -v SILENT ]]; then
        echo "Error: File $file does not exist or is not readable."
      fi
    fi
  done
}

# Be more restrictive with permissions; no one has any business reading things
# that don't belong to them.
if (( EUID != 0 )); then
  umask 027
else
  # Be even less permissive if root.
  umask 077
fi


# Be more restrictive with permissions; no one has any business reading things
# that don't belong to them.
if (( EUID != 0 )); then
  umask 027
else
  # Be even less permissive if root.
  umask 077
fi
